/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: equinn1 (https://sketchfab.com/equinn1)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/finished-desk-project-1d4ea406dc6c4f14b53981660aa72df4
title: Finished Desk project
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/desk/desk.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[27.99, 50.68, -9.88]} rotation={[0, -0.11, 0]} scale={[0.58, 0.93, 0.83]}>
            <mesh geometry={nodes.pCube4_Book_Holder_1_0.geometry} material={materials.Book_Holder_1} />
          </group>
          <group position={[6.17, 0, 4.07]}>
            <group position={[-13.11, 41.63, -6.33]} rotation={[0, 0.52, 0]} scale={0.8}>
              <mesh geometry={nodes.pasted__pCylinder8_Ink_pot_2_0.geometry} material={materials.Ink_pot_2} />
            </group>
            <group position={[-7.56, 41.56, -5.74]} scale={0.8}>
              <mesh geometry={nodes.pasted__pCylinder11_Ink_pot_2_0.geometry} material={materials.Ink_pot_2} />
            </group>
            <group position={[28.98, 37.31, -4.5]} rotation={[-1.64, -0.32, -2.71]} scale={0.8}>
              <mesh geometry={nodes.pasted__pCylinder12_Ink_pot_2_0.geometry} material={materials.Ink_pot_2} />
            </group>
            <group position={[21.6, 37.07, -1.89]} rotation={[1.24, -0.43, -1.71]} scale={0.8}>
              <mesh geometry={nodes.pasted__pCylinder13_Ink_pot_2_0.geometry} material={materials.Ink_pot_2} />
            </group>
            <group position={[24.76, 37.07, 1.88]} rotation={[1.24, -0.43, 3.11]} scale={0.8}>
              <mesh geometry={nodes.pasted__pCylinder14_Ink_pot_2_0.geometry} material={materials.Ink_pot_2} />
            </group>
          </group>
          <group position={[13.97, 0, 0]}>
            <group position={[11.91, 50.1, -4.42]} rotation={[0.03, 0.94, 0.48]} scale={[1.38, 1.13, 1.34]}>
              <mesh geometry={nodes.pasted__pCube7_Fancy_Book_0.geometry} material={materials.Fancy_Book} />
            </group>
          </group>
          <group position={[23.35, 26.96, -4.03]} rotation={[0, 0.48, 0]}>
            <mesh geometry={nodes.pPlane1_lambert11_0.geometry} material={materials.lambert11} />
          </group>
          <group position={[-1.41, 37.57, 5.9]} rotation={[0.4, 0, 0]}>
            <mesh geometry={nodes.pasted__polySurface11_lambert10_0.geometry} material={materials.lambert10} />
          </group>
          <group position={[-3.22, 72.86, 25.24]} rotation={[1.67, -0.64, 1.67]}>
            <group position={[-50.28, 0.83, 37.08]} rotation={[2.16, -0.24, 3.08]}>
              <mesh geometry={nodes.pasted__pPlane1_lambert12_0.geometry} material={materials.lambert12} />
            </group>
          </group>
          <group position={[23.53, 39.45, -23.5]} scale={[1.68, 0.93, 1.11]}>
            <mesh geometry={nodes.pasted__pasted__pCube10_blinn4_0.geometry} material={materials.blinn4} />
          </group>
          <group position={[-20.44, 61.68, -9.63]} scale={0.53}>
            <mesh geometry={nodes.pCylinder8_blinn9_0.geometry} material={materials.blinn9} />
          </group>
          <group position={[6.23, 41.12, -1.11]} rotation={[-Math.PI, 0.66, 0]} scale={0.36}>
            <mesh geometry={nodes.pCylinder10_Pen_Holder_0.geometry} material={materials.Pen_Holder} />
          </group>
          <group position={[19.64, 35.45, 4.01]} rotation={[0, -Math.PI / 6, 0]}>
            <mesh geometry={nodes.pasted__pCylinder7_blinn10_0.geometry} material={materials.blinn10} />
          </group>
          <group position={[0, 0, -0.14]}>
            <mesh geometry={nodes.polySurface58_Desk_0.geometry} material={materials.Desk} />
          </group>
          <group position={[10.87, 41.12, -2.13]} rotation={[-Math.PI, 1.17, 0]} scale={0.36}>
            <mesh geometry={nodes.pCylinder14_Pen_Holder_0.geometry} material={materials.Pen_Holder} />
          </group>
          <group position={[19.98, 38.98, -1.68]} rotation={[0.98, -0.24, -1.36]}>
            <mesh geometry={nodes.pasted__pCylinder10_blinn10_0.geometry} material={materials.blinn10} />
          </group>
          <group position={[25.41, 26.96, 33.84]} rotation={[0, -0.88, 0]}>
            <mesh geometry={nodes.pPlane3_lambert11_0.geometry} material={materials.lambert11} />
          </group>
          <group position={[30.76, 26.79, 18.06]} rotation={[0, -0.41, 0]}>
            <mesh geometry={nodes.pPlane4_lambert11_0.geometry} material={materials.lambert11} />
          </group>
          <group position={[-88.49, 36.41, -109.56]} rotation={[-Math.PI, 1.23, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube12_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[-47.07, 38.32, -123.38]} rotation={[0, Math.PI / 2, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube13_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-68.17, 40.23, -117.48]} rotation={[-Math.PI, 1.39, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube14_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[-87.92, 44.24, -109.15]} rotation={[-Math.PI, 1.23, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube15_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[73.84, 42.3, -75.31]} rotation={[0, Math.PI / 6, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube16_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[-118.32, 46.16, -87.25]} rotation={[-Math.PI, 0.94, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube17_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-114.55, 30.48, -88.95]} rotation={[-Math.PI, 0.94, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube18_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-123, 52.03, -96.76]} rotation={[-Math.PI, 0.89, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube19_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[-73.13, 30.48, 88.16]} rotation={[-Math.PI, -Math.PI / 6, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube20_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[-68.17, 49.97, -132.21]} rotation={[-Math.PI, 1.39, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube21_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[-47.07, 50.18, -123.38]} rotation={[0, Math.PI / 2, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube22_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-88.49, 48.26, -109.56]} rotation={[-Math.PI, 1.23, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube23_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[-69.97, 44.15, -112.84]} rotation={[-Math.PI, 1.3, -Math.PI]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube24_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[9.16, 36.31, -121.95]} rotation={[0, 1.22, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube25_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-12.4, 38.22, -124.12]} rotation={[0, 1.39, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube26_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[106.15, 40.29, -35.29]} rotation={[0, 0.17, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube27_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[-33.8, 42.23, -122.92]} rotation={[0, 1.56, 0]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube28_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[-28.85, 27.23, 0.01]} scale={0.62}>
            <mesh geometry={nodes.pCylinder15_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-25.58, 27.23, 0.01]} scale={0.62}>
            <mesh geometry={nodes.pCylinder16_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-22.25, 27.28, -0.19]} scale={0.62}>
            <mesh geometry={nodes.pCylinder17_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-18.9, 27.28, -0.19]} scale={0.62}>
            <mesh geometry={nodes.pCylinder18_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-27.34, 27.23, 2.5]} scale={0.62}>
            <mesh geometry={nodes.pCylinder19_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-24.07, 27.23, 2.5]} scale={0.62}>
            <mesh geometry={nodes.pCylinder20_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-20.75, 27.28, 2.31]} scale={0.62}>
            <mesh geometry={nodes.pCylinder21_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-28.85, 27.23, 4.45]} scale={0.62}>
            <mesh geometry={nodes.pCylinder22_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-25.58, 27.23, 4.45]} scale={0.62}>
            <mesh geometry={nodes.pCylinder23_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-22.25, 27.28, 4.25]} scale={0.62}>
            <mesh geometry={nodes.pCylinder24_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-18.9, 27.28, 4.25]} scale={0.62}>
            <mesh geometry={nodes.pCylinder25_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-27.34, 27.23, 6.99]} scale={0.62}>
            <mesh geometry={nodes.pCylinder26_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-24.07, 27.23, 6.99]} scale={0.62}>
            <mesh geometry={nodes.pCylinder27_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[-20.75, 27.28, 6.8]} scale={0.62}>
            <mesh geometry={nodes.pCylinder28_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[51.82, -0.03, -22.22]}>
            <mesh geometry={nodes.pCylinder43_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[29.93, 92.23, -6.05]} rotation={[2.63, 0, 0]} scale={1.62}>
            <mesh geometry={nodes.pCylinder44_Pen1_0.geometry} material={materials.Pen1} />
          </group>
          <group position={[64.88, 66.85, 23.35]} rotation={[Math.PI, 0, 0.81]} scale={1.62}>
            <mesh geometry={nodes.pCylinder45_blinn8_0.geometry} material={materials.blinn8} />
          </group>
          <group position={[-3.41, 90.19, 14.41]} rotation={[3, 0.1, -0.61]} scale={1.62}>
            <mesh geometry={nodes.pCylinder46_Pen2_0.geometry} material={materials.Pen2} />
          </group>
          <group position={[-26.69, 11.42, 15.43]} rotation={[-Math.PI, 0, -2.48]} scale={1.62}>
            <mesh geometry={nodes.pCylinder47_blinn8_0.geometry} material={materials.blinn8} />
          </group>
          <group position={[-0.85, -4.03, 18]} rotation={[-2.27, -0.97, -2.09]} scale={1.62}>
            <mesh geometry={nodes.pCylinder48_Pen2_0.geometry} material={materials.Pen2} />
          </group>
          <group position={[36.2, 1.07, 17.06]} rotation={[2.14, -1.25, 2.24]} scale={1.62}>
            <mesh geometry={nodes.pCylinder49_Pen2_0.geometry} material={materials.Pen2} />
          </group>
          <group position={[21.91, -8.47, -7.45]} rotation={[-0.26, 0, 0]} scale={1.62}>
            <mesh geometry={nodes.pCylinder50_Pen1_0.geometry} material={materials.Pen1} />
          </group>
          <group position={[53.93, 22.45, -8.07]} rotation={[0.54, -0.47, 0.91]} scale={1.62}>
            <mesh geometry={nodes.pCylinder51_Pen2_0.geometry} material={materials.Pen2} />
          </group>
          <group position={[24.93, -5.22, -11.55]} rotation={[-0.85, 0.77, 0.83]} scale={1.62}>
            <mesh geometry={nodes.pCylinder52_Pen1_0.geometry} material={materials.Pen1} />
          </group>
          <group position={[29.09, -5.07, 0.19]} rotation={[-0.06, -0.86, 0.05]} scale={1.62}>
            <mesh geometry={nodes.pCylinder53_Pen2_0.geometry} material={materials.Pen2} />
          </group>
          <group position={[11.23, -5.96, 19.59]} rotation={[-2.95, -1.07, -2.87]} scale={1.62}>
            <mesh geometry={nodes.pCylinder54_blinn8_0.geometry} material={materials.blinn8} />
          </group>
          <group position={[11.91, 30.23, 13.07]} scale={0.8}>
            <mesh geometry={nodes.pCylinder55_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[7, 30.23, 13.07]} scale={0.8}>
            <mesh geometry={nodes.pCylinder56_blinn2_0.geometry} material={materials.blinn2} />
          </group>
          <group position={[51.64, 35.42, 22.17]} rotation={[2.84, 0, 1.57]} scale={1.62}>
            <mesh geometry={nodes.pCylinder57_blinn8_0.geometry} material={materials.blinn8} />
          </group>
          <group position={[-65.44, 162.31, 8.95]} rotation={[Math.PI, 0, -1.99]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube29_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[-63.46, 162.31, 10.71]} rotation={[Math.PI, 0, -1.99]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube30_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[-4.79, 174.18, 10.43]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube31_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-37.92, 168.79, 10.43]} rotation={[Math.PI, 0, -1.86]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube32_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-61.19, 162.31, 10.71]} rotation={[Math.PI, 0, -1.99]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube33_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
          <group position={[73.1, 160.27, 8.95]} rotation={[Math.PI, 0, -1.11]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube34_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[93.95, 144.06, 8.95]} rotation={[Math.PI, 0, -0.88]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube35_Thin_Book_0.geometry} material={materials.Thin_Book} />
          </group>
          <group position={[-68.91, 152.86, 10.43]} rotation={[Math.PI, 0, -2.15]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube36_Blue_Thin_Book_0.geometry} material={materials.Blue_Thin_Book} />
          </group>
          <group position={[-77.77, 142.24, 9.59]} rotation={[Math.PI, 0, -2.28]} scale={[1.2, 0.98, 1.16]}>
            <mesh geometry={nodes.pCube37_Pink_Thin_Book_0.geometry} material={materials.Pink_Thin_Book} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/desk/desk.glb')
